### ISSUE TITLE
Upgrade to 1.3.0 failed for some modules

### ISSUE THREAD

**Issue by djvl** [GoWired/GoWired-Project#27]
Today I spend some time to upgrade the software on some MCU modules (2SSR & RGBW) from 1.2.0 to the new 1.3.0 release but had to roll back to 1.2.0 because of restarting node issues. It appeared to be an issue with the digital inputs, as soon as I disabled the PIRs connected to the inputs the restarting issue went away. I did not had the time to dig deeper, but will try to have another look at it soon. Any idea how to troubleshoot this kind of issue? I am using a MQTT enabled gateway.

**Comment by feanor-anglin** [comment]
1.3.0 uses entirely different code for reading inputs, so your feedback is truly valuable to me. I am already aware of some issues when using it with security sensors. Some improvements has already been developed, so if you give me a few days, I should come up with a fix. In the meantime, could you give me some more details of what exactly you use, how is it connected and configured?

**Comment by djvl** [comment]
Sure, no problem. I will describe one of the failing nodes in more detail about how it is setup. First of all on the hardware side. The MCU module (1.0) is used in combination with a 2SSR shield. The PIR (Satel Aqua Ring 12v) is connected to an external 12v power source and the signal cable (2x NC) is connected to the MCU I/O-2 (I/O-1 is not yet being used on this node).

I/O-2 Arduino PIN4 (yellow cable) to NC on PIR
I/O-2 GND (red cable) to NC on PIR

On the software side I like to follow the defaults as much as possible. To prevent any upgrade issues I chose to use the ‘Configuration.h’ which comes with the new release and change only the MY_NODE_ID, SN, SV (was 1.2 on the 1.3 release) and dependent on the module one of the following: DOUBLE_RELAY, DIMMER or RGBW. In this case it is  DOUBLE_RELAY.

If there is more you want me to check or test, please let me know.

**Comment by feanor-anglin** [comment]
@djvl thank you for your cooperation. I've pushed a fix to dev branch, could you test it and post me the result? It works for me on a slightly different hardware. If you are using your modules with PIR sensors you may want to invert input logic in Configuration.h:
![image](https://user-images.githubusercontent.com/44804352/164230863-87d86d75-03fd-4fb0-90ed-e0a5bc6ea337.png)
Simply change _false_ to _true_ next to the _INVERT_X_ parameter.

**Comment by djvl** [comment]
@feanor-anglin I can confirm the fix works for me as well. Thank you for your quick response and solution. I will try the suggestion about the invert logic when I have more time as it will also involve a change on my controller. Thanks again!
