### ISSUE TITLE
Power sensor reports unexpeced value

### ISSUE THREAD

**Issue by djvl** [GoWired/GoWired-Project#28]
I am using openHAB as home automation controller in combination with GoWired and receive events over MQTT. Since I have added the topics for power and error readings the openHAB logging started to show the following warnings:

[WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload ' 0' not supported by type 'NumberValue'

It appears to be an issue with the power reading as can be seen on the following mosquitto_sub logging:
```
gwo/7/9/1/0/17 30
gwo/7/9/1/0/17  0  <-- there is a leading space in front of the 0
```
When for instance the lighting is turned off the reported value goes to ' 0' where I expected it to be '0'.

Is this intended or a bug?

**Comment by feanor-anglin** [comment]
Hi @djvl, thanks for posting. I can't see any reason for such behavior. This is the line, that sends power value to the controller:
```
send(msgPS.set(PS.CalculatePower(Current, COSFI), 0));
```
_PS.CalculatePower()_ returns float. So it seems it is related to MySensors or MQTT.

**Comment by djvl** [comment]
Okay, I see. I will have a look at both MySensors and MQTT. If I come across a solution I will report back.
